version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: backend
    container_name: api_container
    links:
      - mysql
    restart: always
    tty: true
    stdin_open: true
    privileged: true
    command: bin/sh
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Tokyo"
    # volumes:
    #   - ./backend/python:/var/www/

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    restart: always
    container_name: frontend_container
    tty: true
    stdin_open: true
    privileged: true
    command: bin/sh
    links:
      - backend
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Tokyo"
    # volumes:
    #   - ./web/vue/dist:/home/www/contents:ro

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vue-fastapi-db
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyoa
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306