version: "3"

services:
  frontend:
    container_name: frontend_container
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    restart: always
    tty: true
    stdin_open: true
    privileged: true
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./frontend :/frontend:cached
    # volumes:
    #   - ./web/vue/dist:/home/www/contents:ro
  backend:
    container_name: api_container
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: backend
    restart: always
    tty: true
    stdin_open: true
    privileged: true
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./api :/api:cached
    # volumes:
    #   - ./backend/python:/var/www/
  db:
    image: mariadb:latest
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vue-fastapi-db
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: secret
      TZ: Asia/Tokyoa
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
  prod:
    container_name: production_container
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    tty: true
    stdin_open: true
    privileged: true
    ports:
      - 80:80
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./frontend/dist :/usr/share/nginx/html